# Generated by Django 5.2.10 on 2026-01-16 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=1000, unique=True)),
                ('meal_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_category', models.CharField(choices=[('breakfast', 'Сніданки'), ('main_course', 'Основні страви'), ('salad', 'Салати'), ('dessert', 'Десерти'), ('beverage', 'Напої')], max_length=30)),
                ('status', models.BooleanField(choices=[(True, 'Доступний'), (False, 'Недоступний')], default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
