# Generated by Django 5.2.10 on 2026-01-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='meal_description',
            field=models.TextField(null=True),
        ),
    ]
